<!DOCTYPE html>
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@ taglib prefix="s" uri="/struts-tags" %>

<html lang="en">

<head>
    <jsp:include page="htmlHead.jsp"/>
    <title><s:property value="%{getText('tituloId')}"/></title>
    <script type="text/javascript" src="js/sp.js"></script>
    <script type="text/javascript" src="js/base64.js"></script>
</head>
<body>

<!--START HEADER-->
<header class="header">
    <div class="container">
        <h1><s:property value="%{getText('tituloCabeceraId')}"/></h1>
    </div>
</header>
<!--END HEADER-->
<div class="container">
    <div class="row">
        <div class="tab-content">
            <div role="tabpanel" class="tab-pane fade in active" id="tab-02">
                <div class="col-md-12">
                    <h2><s:property value="%{providerName}"/>
                        <%--<span class="sub-title"><s:property value="%{getText('eIDASMode')}"/></span>--%>
                        <span class="sub-title">SamlRequest generated by the SP</span>
                    </h2>
                </div>
                <jsp:include page="leftColumn.jsp"/>
                <div class="col-md-6">
                    <form id="countrySelector" name="countrySelector" action="<s:property value="defaultActionUrl" />" target="_parent" onsubmit="setSAMRequestMethod();">
                        <input type="hidden" id="postLocationUrl" name="postLocationUrl" value="<s:property value="postActionUrl" />">
                        <input type="hidden" id="redirectLocationUrl" name="redirectLocationUrl" value="<s:property value="redirectActionUrl" />">
                        <div class="form-group">
                            <label for="country"><s:property value="%{getText('destinationCountryId')}"/></label>
                            <input type="text" name="country" value="<s:property value="citizen"/>" id="country" class="form-control"/>
                        </div>
                        <div class="form-group">
                            <label for="country"><s:property value="%{getText('relayState')}"/></label>
                            <input type="text" id="relayState" name="RelayState" value="MyRelayState" class="form-control"/>
                        </div>
                        <div class="form-group">
                            <label for="SAMLRequest"><s:property value="%{getText('SAMLRequestId')}"/></label>
                            <textarea class="form-control" rows="8" id="SAMLRequest" name="SAMLRequest"><s:property value="samlRequest"/></textarea>
                        </div>
                        <div class="form-group">
                            <div class="radio-inline-group">
                                <div class="radio radio-info radio-inline">
                                    <input type="radio" name="sendmethods" id="postmethod" value="POST" checked onChange="ajaxChangeHttpMethod('samlRequestXML','changeProtocolBinding.action', receiveSignedRequest,errorAjaxRequest)"/>
                                    <label for="postmethod">HTTP Post Binding</label><br/>
                                </div>
                                <div class="radio radio-info radio-inline">
                                    <input type="radio" name="sendmethods" id="getmethod" value="GET" onChange="ajaxChangeHttpMethod('samlRequestXML','changeProtocolBinding.action', receiveSignedRequest,errorAjaxRequest)"/>
                                    <label for="getmethod">HTTP Redirect Binding</label>
                                </div>
                            </div>
                        </div>
                        <div class="button-group">
                            <button id="submit_saml" type="button" class="btn btn-default btn-lg btn-block" onclick="$('#countrySelector').submit();">Submit</button>
                        </div>
                    </form>
                    <form id="samlRequestXML" name="samlRequestXML" action="reSign">
                        <input type="hidden" id="samlRequestBinding" name="samlRequestBinding" value="POST">
                        <input type="hidden" id="samlRequestLocation" name="samlRequestLocation" value="<s:property value="defaultActionUrl" />">
                        <input type="hidden" id="citizenCountryCode" name="citizenCountryCode" value="<s:property value="citizen"/>">
                        <div class="button-group">
                            <button type="button" id="encodeButton" class="btn btn-default btn-lg btn-block" OnClick="signAndEncodeSAMLRequest();">Re-sign and Encode</button>
                            <button type="button" id="decodeButton" class="btn btn-default btn-lg btn-block" OnClick="decodeSAMLRequest();">Decode</button>
                        </div>
                        <div class="form-group">
                            <label for="country"><s:property value="%{getText('SAMLRequestXMLId')}"/></label>
                            <textarea class="form-control" rows="8" id="samlRequestXML" name="samlRequestXML"><s:property value="samlRequestXML"/></textarea>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
<jsp:include page="footer.jsp"/>
</body>
</html>
